//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Sales.Entities.Resoueces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrderMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrderMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Sales.Entities.Resoueces.CreateOrderMessages", typeof(CreateOrderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("|", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe proporcionar el identificador del cliente..
        /// </summary>
        internal static string CustomerIdRequired {
            get {
                return ResourceManager.GetString("CustomerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del identificador del cliente debe ser 5..
        /// </summary>
        internal static string CustomerIdRequiredLength {
            get {
                return ResourceManager.GetString("CustomerIdRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar al menos un producto de la orden..
        /// </summary>
        internal static string OrderDetailsNotEmpty {
            get {
                return ResourceManager.GetString("OrderDetailsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el identificador del producto..
        /// </summary>
        internal static string ProductIdGreaterThanZero {
            get {
                return ResourceManager.GetString("ProductIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar la cantidad ordernda del producto..
        /// </summary>
        internal static string QuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("QuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima de la dirección es 60..
        /// </summary>
        internal static string ShipAddressMaximumLength {
            get {
                return ResourceManager.GetString("ShipAddressMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe proporcionar la dirección de envío..
        /// </summary>
        internal static string ShipAddressRequired {
            get {
                return ResourceManager.GetString("ShipAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima de la ciudad es 15..
        /// </summary>
        internal static string ShipCityMaximumLength {
            get {
                return ResourceManager.GetString("ShipCityMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar al menos 3 caracteres del nombre de la ciudad..
        /// </summary>
        internal static string ShipCityMinimunLength {
            get {
                return ResourceManager.GetString("ShipCityMinimunLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe proporcionar la ciudad de envío..
        /// </summary>
        internal static string ShipCityRequired {
            get {
                return ResourceManager.GetString("ShipCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longittud máxima del país es 15..
        /// </summary>
        internal static string ShipCountryMaximumLength {
            get {
                return ResourceManager.GetString("ShipCountryMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar al menos 3 caracteres..
        /// </summary>
        internal static string ShipCountryMinimumLength {
            get {
                return ResourceManager.GetString("ShipCountryMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe proporcionar el país de envío..
        /// </summary>
        internal static string ShipCountryRequired {
            get {
                return ResourceManager.GetString("ShipCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud máxima del código postal es 10..
        /// </summary>
        internal static string ShipPostalCodeMaximumLength {
            get {
                return ResourceManager.GetString("ShipPostalCodeMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe especificar el precio..
        /// </summary>
        internal static string UnitPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("UnitPriceGreaterThanZero", resourceCulture);
            }
        }
    }
}
